/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tp.visao;

/**
 *
 * @author gabri
 */
public class tela extends javax.swing.JPanel {

    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2Visor = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton8plus = new javax.swing.JButton();
        jButton9_4 = new javax.swing.JButton();
        jButton10_2 = new javax.swing.JButton();
        jButton11_3 = new javax.swing.JButton();
        jButton12AllClean = new javax.swing.JButton();
        jButton13_1 = new javax.swing.JButton();
        jButton14mult = new javax.swing.JButton();
        jButton15_5 = new javax.swing.JButton();
        jButton16_6 = new javax.swing.JButton();
        jButton17menos = new javax.swing.JButton();
        jButton18exp = new javax.swing.JButton();
        jButton19V = new javax.swing.JButton();
        jButton20_0 = new javax.swing.JButton();
        jButton21_9 = new javax.swing.JButton();
        jButton22div = new javax.swing.JButton();
        jButton23_7 = new javax.swing.JButton();
        jButton24_8 = new javax.swing.JButton();
        jButton25Erase = new javax.swing.JButton();
        jButton26raiz = new javax.swing.JButton();
        jButton27igual = new javax.swing.JButton();
        jButton28mudSinal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Operacoes = new javax.swing.JTextArea();

        jTextArea2Visor.setColumns(20);
        jTextArea2Visor.setRows(5);
        jScrollPane2.setViewportView(jTextArea2Visor);

        jButton8plus.setText("+");
        jButton8plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8plusActionPerformed(evt);
            }
        });

        jButton9_4.setText("4");
        jButton9_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9_4ActionPerformed(evt);
            }
        });

        jButton10_2.setText("2");
        jButton10_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10_2ActionPerformed(evt);
            }
        });

        jButton11_3.setText("3");
        jButton11_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11_3ActionPerformed(evt);
            }
        });

        jButton12AllClean.setText("AC");
        jButton12AllClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12AllCleanActionPerformed(evt);
            }
        });

        jButton13_1.setText("1");
        jButton13_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13_1ActionPerformed(evt);
            }
        });

        jButton14mult.setText("*");

        jButton15_5.setText("5");

        jButton16_6.setText("6");

        jButton17menos.setText("-");

        jButton18exp.setText("x^2");
        jButton18exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18expActionPerformed(evt);
            }
        });

        jButton19V.setText(",");
        jButton19V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19VActionPerformed(evt);
            }
        });

        jButton20_0.setText("0");
        jButton20_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20_0ActionPerformed(evt);
            }
        });

        jButton21_9.setText("9");
        jButton21_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21_9ActionPerformed(evt);
            }
        });

        jButton22div.setText("/");
        jButton22div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22divActionPerformed(evt);
            }
        });

        jButton23_7.setText("7");
        jButton23_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23_7ActionPerformed(evt);
            }
        });

        jButton24_8.setText("8");
        jButton24_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24_8ActionPerformed(evt);
            }
        });

        jButton25Erase.setText("X");
        jButton25Erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25EraseActionPerformed(evt);
            }
        });

        jButton26raiz.setText("R");
        jButton26raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26raizActionPerformed(evt);
            }
        });

        jButton27igual.setText("=");
        jButton27igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27igualActionPerformed(evt);
            }
        });

        jButton28mudSinal.setText("+/-");
        jButton28mudSinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28mudSinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton13_1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton9_4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19V, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23_7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15_5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20_0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton24_8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11_3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16_6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21_9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12AllClean, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17menos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton22div, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18exp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14mult, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8plus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton25Erase, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton26raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton28mudSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton27igual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton27igual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8plus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12AllClean, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14mult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16_6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17menos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton18exp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21_9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton22div, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton23_7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton24_8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton26raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton25Erase, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20_0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19V, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton28mudSinal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1Operacoes.setColumns(20);
        jTextArea1Operacoes.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Operacoes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8plusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8plusActionPerformed

    private void jButton10_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10_2ActionPerformed

    private void jButton11_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11_3ActionPerformed

    private void jButton12AllCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12AllCleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12AllCleanActionPerformed

    private void jButton9_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9_4ActionPerformed

    private void jButton18expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18expActionPerformed

    private void jButton19VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19VActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19VActionPerformed

    private void jButton20_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20_0ActionPerformed

    private void jButton21_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21_9ActionPerformed

    private void jButton22divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22divActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22divActionPerformed

    private void jButton23_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23_7ActionPerformed

    private void jButton24_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24_8ActionPerformed

    private void jButton25EraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25EraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25EraseActionPerformed

    private void jButton26raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26raizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26raizActionPerformed

    private void jButton27igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27igualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27igualActionPerformed

    private void jButton28mudSinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28mudSinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28mudSinalActionPerformed

    private void jButton13_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13_1ActionPerformed
        String num = "1";
        
        if (jButton13_1.isEnabled()){
            jTextArea2Visor.setText(num);
        }
    }//GEN-LAST:event_jButton13_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10_2;
    private javax.swing.JButton jButton11_3;
    private javax.swing.JButton jButton12AllClean;
    private javax.swing.JButton jButton13_1;
    private javax.swing.JButton jButton14mult;
    private javax.swing.JButton jButton15_5;
    private javax.swing.JButton jButton16_6;
    private javax.swing.JButton jButton17menos;
    private javax.swing.JButton jButton18exp;
    private javax.swing.JButton jButton19V;
    private javax.swing.JButton jButton20_0;
    private javax.swing.JButton jButton21_9;
    private javax.swing.JButton jButton22div;
    private javax.swing.JButton jButton23_7;
    private javax.swing.JButton jButton24_8;
    private javax.swing.JButton jButton25Erase;
    private javax.swing.JButton jButton26raiz;
    private javax.swing.JButton jButton27igual;
    private javax.swing.JButton jButton28mudSinal;
    private javax.swing.JButton jButton8plus;
    private javax.swing.JButton jButton9_4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1Operacoes;
    private javax.swing.JTextArea jTextArea2Visor;
    // End of variables declaration//GEN-END:variables
}
