/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tp.tela;
import projetocalculadora.ProjetoCalculadora;

/**
 *
 * @author gabri
 */
public class TelaCalc extends javax.swing.JFrame {
     ProjetoCalculadora calculo = new ProjetoCalculadora();
    /**
     * Creates new form TelaCalc
     */
    public TelaCalc() {
        initComponents();
        jTextArea1Visor.setEnabled(false);
        jTextArea2TelaOperacoes.setEnabled(false);
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Visor = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2TelaOperacoes = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1num7 = new javax.swing.JButton();
        jButton2Igual = new javax.swing.JButton();
        jButton3num5 = new javax.swing.JButton();
        jButton4num6 = new javax.swing.JButton();
        jButton5Subtracao = new javax.swing.JButton();
        jButton6Multiplicacao = new javax.swing.JButton();
        jButton7num1 = new javax.swing.JButton();
        jButton8num8 = new javax.swing.JButton();
        jButton9num9 = new javax.swing.JButton();
        jButton10limparTudo = new javax.swing.JButton();
        jButton11soma = new javax.swing.JButton();
        jButton12num4 = new javax.swing.JButton();
        jButton13num3 = new javax.swing.JButton();
        jButton14num2 = new javax.swing.JButton();
        jButton15Divisao = new javax.swing.JButton();
        jButton16Exponenciacao = new javax.swing.JButton();
        jButton17Virgula = new javax.swing.JButton();
        jButton18num0 = new javax.swing.JButton();
        jButton19LimparNum = new javax.swing.JButton();
        jButton20Raiz = new javax.swing.JButton();
        jButton21TrocaTroca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1Visor.setColumns(20);
        jTextArea1Visor.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Visor);

        jTextArea2TelaOperacoes.setColumns(20);
        jTextArea2TelaOperacoes.setRows(5);
        jScrollPane2.setViewportView(jTextArea2TelaOperacoes);

        jButton1num7.setText("7");
        jButton1num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1num7ActionPerformed(evt);
            }
        });

        jButton2Igual.setText("=");
        jButton2Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2IgualActionPerformed(evt);
            }
        });

        jButton3num5.setText("5");
        jButton3num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3num5ActionPerformed(evt);
            }
        });

        jButton4num6.setText("6");
        jButton4num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4num6ActionPerformed(evt);
            }
        });

        jButton5Subtracao.setText("-");
        jButton5Subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5SubtracaoActionPerformed(evt);
            }
        });

        jButton6Multiplicacao.setText("*");
        jButton6Multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6MultiplicacaoActionPerformed(evt);
            }
        });

        jButton7num1.setText("1");
        jButton7num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7num1ActionPerformed(evt);
            }
        });

        jButton8num8.setText("8");
        jButton8num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8num8ActionPerformed(evt);
            }
        });

        jButton9num9.setText("9");
        jButton9num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9num9ActionPerformed(evt);
            }
        });

        jButton10limparTudo.setText("AC");
        jButton10limparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10limparTudoActionPerformed(evt);
            }
        });

        jButton11soma.setText("+");
        jButton11soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11somaActionPerformed(evt);
            }
        });

        jButton12num4.setText("4");
        jButton12num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12num4ActionPerformed(evt);
            }
        });

        jButton13num3.setText("3");
        jButton13num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13num3ActionPerformed(evt);
            }
        });

        jButton14num2.setText("2");
        jButton14num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14num2ActionPerformed(evt);
            }
        });

        jButton15Divisao.setText("/");

        jButton16Exponenciacao.setText("x^2");

        jButton17Virgula.setText(",");
        jButton17Virgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17VirgulaActionPerformed(evt);
            }
        });

        jButton18num0.setText("0");
        jButton18num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18num0ActionPerformed(evt);
            }
        });

        jButton19LimparNum.setText("X");

        jButton20Raiz.setText("R");

        jButton21TrocaTroca.setText("+/-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1num7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8num8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9num9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10limparTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11soma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton12num4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButton3num5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7num1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton17Virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton18num0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton14num2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4num6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton13num3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton5Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton6Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton15Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton16Exponenciacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton19LimparNum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton20Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton21TrocaTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2Igual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1num7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8num8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9num9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10limparTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11soma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3num5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4num6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12num4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton13num3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton14num2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton15Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton16Exponenciacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton7num1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton17Virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18num0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19LimparNum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21TrocaTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2IgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2IgualActionPerformed

    private void jButton5SubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5SubtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5SubtracaoActionPerformed

    private void jButton6MultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6MultiplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MultiplicacaoActionPerformed

    private void jButton9num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9num9ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux()+"9");
        jTextArea1Visor.setText(jTextArea1Visor.getText()+"9");
    }//GEN-LAST:event_jButton9num9ActionPerformed

    private void jButton10limparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10limparTudoActionPerformed
        // TODO add your handling code here:
        jTextArea1Visor.setText("");
    }//GEN-LAST:event_jButton10limparTudoActionPerformed

    private void jButton11somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11somaActionPerformed
        // TODO add your handling code here:
        
        if(calculo.getNum1() == 0){
             
        } else {
             calculo.setNum2(Float.parseFloat(calculo.getNumAux()));
        }
        
        
        
        calculo.setNum1(Float.parseFloat(calculo.getNumAux()));
        
        calculo.setResult(calculo.getNum1()+calculo.getNum2());
        
        //System.out.println(calculo.getNum1());
        //System.out.println(calculo.getNum2());
        
        jTextArea2TelaOperacoes.setText(Float.toString(calculo.getResult()));
        
        calculo.setNumAux(calculo.getVazio());
        jTextArea1Visor.setText("+ ");
    }//GEN-LAST:event_jButton11somaActionPerformed

    private void jButton7num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7num1ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux()+"1");
        jTextArea1Visor.setText(jTextArea1Visor.getText()+"1");
       
    }//GEN-LAST:event_jButton7num1ActionPerformed

    private void jButton1num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1num7ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux()+"7");
         jTextArea1Visor.setText(jTextArea1Visor.getText()+"7");
    }//GEN-LAST:event_jButton1num7ActionPerformed

    private void jButton14num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14num2ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux() + "2");
         jTextArea1Visor.setText(jTextArea1Visor.getText()+"2");
    }//GEN-LAST:event_jButton14num2ActionPerformed

    private void jButton13num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13num3ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux()+"3");
         jTextArea1Visor.setText(jTextArea1Visor.getText() + "3");
    }//GEN-LAST:event_jButton13num3ActionPerformed

    private void jButton12num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12num4ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux()+"4");
         jTextArea1Visor.setText(jTextArea1Visor.getText()+"4");
    }//GEN-LAST:event_jButton12num4ActionPerformed

    private void jButton3num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3num5ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux()+"5");
         jTextArea1Visor.setText(jTextArea1Visor.getText() + "5");
    }//GEN-LAST:event_jButton3num5ActionPerformed

    private void jButton4num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4num6ActionPerformed
        // TODO add your handling code here:
        calculo.setNumAux(calculo.getNumAux()+"6");
         jTextArea1Visor.setText(jTextArea1Visor.getText() + "6");
    }//GEN-LAST:event_jButton4num6ActionPerformed

    private void jButton8num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8num8ActionPerformed
        // TODO add your handling code here:
         calculo.setNumAux(calculo.getNumAux()+"8");
         jTextArea1Visor.setText(jTextArea1Visor.getText()+"8");
    }//GEN-LAST:event_jButton8num8ActionPerformed

    private void jButton18num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18num0ActionPerformed
        // TODO add your handling code here:
         calculo.setNumAux(calculo.getNumAux()+"0");
         jTextArea1Visor.setText(jTextArea1Visor.getText()+"0");
    }//GEN-LAST:event_jButton18num0ActionPerformed

    private void jButton17VirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17VirgulaActionPerformed
        // TODO add your handling code here:
         calculo.setNumAux(calculo.getNumAux()+".");
         jTextArea1Visor.setText(jTextArea1Visor.getText()+".");
    }//GEN-LAST:event_jButton17VirgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10limparTudo;
    private javax.swing.JButton jButton11soma;
    private javax.swing.JButton jButton12num4;
    private javax.swing.JButton jButton13num3;
    private javax.swing.JButton jButton14num2;
    private javax.swing.JButton jButton15Divisao;
    private javax.swing.JButton jButton16Exponenciacao;
    private javax.swing.JButton jButton17Virgula;
    private javax.swing.JButton jButton18num0;
    private javax.swing.JButton jButton19LimparNum;
    private javax.swing.JButton jButton1num7;
    private javax.swing.JButton jButton20Raiz;
    private javax.swing.JButton jButton21TrocaTroca;
    private javax.swing.JButton jButton2Igual;
    private javax.swing.JButton jButton3num5;
    private javax.swing.JButton jButton4num6;
    private javax.swing.JButton jButton5Subtracao;
    private javax.swing.JButton jButton6Multiplicacao;
    private javax.swing.JButton jButton7num1;
    private javax.swing.JButton jButton8num8;
    private javax.swing.JButton jButton9num9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1Visor;
    private javax.swing.JTextArea jTextArea2TelaOperacoes;
    // End of variables declaration//GEN-END:variables
}
